[package]
name = "mangashelf"
version = "0.1.0"
description = "本地漫画管理器"
authors = ["pancake114514"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "mangashelf_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
image = { version = "0.25", features = ["jpeg", "png", "bmp", "webp", "gif", "tiff"] }
image-webp = "0.2"
sha2 = "0.10"
hex = "0.4"
log = "0.4"
env_logger = "0.11"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
